<?php
$this->title = "My Albums";
$this->headTitle($this->title);
?>
<p><a href="<?php echo $this->url(array('controller' => 'Index', 'action' => 'add')); ?>">Add new album</a></p>
<table>
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->albums as $album) : ?>
        <tr>
            <td><?php echo $this->escape($album->title); ?></td>
            <td><?php echo $this->escape($album->artist); ?></td>
            <td>
                <a href="<?php
                echo $this->url(array('controller' => 'Index',
                    'action' => 'edit', 'id' => $album->id));
                ?>">Edit</a>
                <a href="<?php
                   echo $this->url(array('controller' => 'Index',
                       'action' => 'delete', 'id' => $album->id));
                   ?>">Delete</a>
            </td>
        </tr>
<?php endforeach; ?>
        <h1>This is for testing.... 20130526</h1>        
</table>